config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'lists#index'

  resources :tasks do
    member do
      patch :update_status
    end
  end

  resources :lists

  get '/dashboard', to: 'dashboards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true
  has_many :tasks, dependent: :restrict_with_error
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true, length: {maximum: 30}
  validates :status, inclusion: { in: %w(todo progress done), message: '%{value} is not a valid status' }, presence: true
  validates :priority, inclusion: { in: %w(high medium low), message: '%{value} is not a valid priority' }
  validates :description, length: { maximum: 200 }

  belongs_to :list
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :lists, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout

  private
    def layout
    if devise_controller? && resource_name == :user && action_name == 'new' 
        "devise" 
    else 
        "application" 
    end
      
        #is_a?(Devise::SessionsController) ? false : 'application'

      # or turn layout off for every devise controller:
      # devise_controller? && "application"
    end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @lists = current_user.lists.all
    @tasks = current_user.tasks.all
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_permission, only: %i[show edit update destroy]
  before_action :set_list, only: %i[show edit update destroy]

  # GET /lists or /lists.json
  def index
    @lists = current_user.lists.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = current_user.lists.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = current_user.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_path, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_path, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    respond_to do |format|
      if @list.destroy
        format.html { redirect_to root_path, notice: "List was successfully destroyed." }
        format.json { head :no_content }
      else
        format.html { redirect_to root_path, alert: @list.errors.messages[:base][0] }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name)
    end

    def require_permission
      if List.find(params[:id]).user != current_user
        redirect_to root_path, alert: "You don't have permission to do that."
      end
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :require_permission, only: %i[show edit update destroy update_status]
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = current_user.tasks.all
  end

  def update_status
    @task = Task.find(params[:id])
    @task.update(status: params[:status])
    redirect_to root_path, notice: "Status changed to #{@task.status}"
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = current_user.tasks.new(task_params)
    @task.status = 'todo'

    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_path, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :status, :priority, :list_id, :description)
    end

    def require_permission
      if Task.find(params[:id]).user != current_user
        redirect_to root_path, flash: { error: "You do not have permission to do that." }
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/dashboards/index.html.erb
<div class="row m-5 rounded p-5" style="background: #FFF;">
  <h1>Dashboard</h1>
  <hr>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card text-center card-info m-3">
          <div class="card-body">
              <h5 class="card-title">Total Lists <i class="fa-solid fa-table-list"></i></h5>
              <hr>
              <h5 class="card-text"><%= @lists.count %> Lists</h5>
          </div>
      </div>    
      <div class="card text-center card-info m-3">
          <div class="card-body">
              <h5 class="card-title">Total Tasks <i class="fa-solid fa-list-check"></i></h5>
              <hr>
              <h5 class="card-text"><%= @tasks.count %> Tasks</h5>
          </div>
      </div>            

    </div>
    <hr>
    <div class="row justify-content-md-center">
        <div class="card text-center card-info m-3">
            <div class="card-body">
                <h5 class="card-title">ToDo <i class="fa-solid fa-triangle-exclamation"></i></h5>
                <hr>
                <h5 class="card-text"><%= @tasks.where(status: 'todo').count %> Tasks</h5>
            </div>
        </div>
        <div class="card text-center card-info m-3">
            <div class="card-body">
                <h5 class="card-title">In Progress <i class="fa-solid fa-spinner"></i></i></h5>
                <hr>
                <h5 class="card-text"><%= @tasks.where(status: 'progress').count %> Tasks</h5>
            </div>
        </div>
        <div class="card text-center card-info m-3">
            <div class="card-body">
                <h5 class="card-title">Done <i class="fa-solid fa-check"></i></i></h5>
                <hr>
                <h5 class="card-text"><%= @tasks.where(status: 'done').count %> Tasks</h5>
            </div>
        </div>            
    </div>
    <% if @tasks.count > 0 %>
      <% @count = @tasks.count %>
      <h3 class="mt-3">To Do:</h3>
      <div class="progress" style="width: 35%;">
        <% @percentTodo =  (@tasks.where(status: 'todo').count.to_f / @count * 100).to_i  %>
        <div class="progress-bar bg-warning" role="progressbar" aria-label="Warning example" style="width: <%= @percentTodo %>%" aria-valuenow="<%= @percentTodo %>" aria-valuemin="0" aria-valuemax="100"><%= @percentTodo %>%</div>
      </div>
      <h3 class="mt-3">In Progress:</h3>
      <div class="progress" style="width: 35%;">
        <% @percentProgr =  (@tasks.where(status: 'progress').count.to_f / @count * 100).to_i %>
        <div class="progress-bar bg-info" role="progressbar" aria-label="Info example" style="width: <%= @percentProgr %>%" aria-valuenow="<%= @percentProgr %>" aria-valuemin="0" aria-valuemax="100"><%= @percentProgr %>%</div>
      </div>
      <h3 class="mt-3">Done:</h3>
      <div class="progress" style="width: 35%;">
        <% @percentDone =  (@tasks.where(status: 'done').count.to_f / @count * 100).to_i %>
        <div class="progress-bar bg-success" role="progressbar" aria-label="Success example" style="width: <%= @percentDone %>%" aria-valuenow="<%= @percentDone %>" aria-valuemin="0" aria-valuemax="100"><%= @percentDone%>%</div>
      </div>

      <h2 class="row justify-content-md-center mt-5">Tasks per day</h2>
      <%= line_chart @tasks.group_by_day(:created_at).count,  colors: ["#FF700A"]%>
      
      <h2 class="row justify-content-md-center mt-5">Priority distribution</h2>
      <%= pie_chart @tasks.group(:priority).count %>
      
      <h3 class="mt-3">Low Priority:</h3>
      <div class="progress" style="width: 35%;">
        <% @percentLow =  (@tasks.where(priority: 'low').count.to_f / @count * 100).to_i  %>
        <div class="progress-bar bg-success" role="progressbar" aria-label="Warning example" style="width: <%= @percentLow %>%" aria-valuenow="<%= @percentLow %>" aria-valuemin="0" aria-valuemax="100"><%= @percentLow %>%</div>
      </div>
      <h3 class="mt-3">Medium Priority:</h3>
      <div class="progress" style="width: 35%;">
        <% @percentMedium =  (@tasks.where(priority: 'medium').count.to_f / @count * 100).to_i %>
        <div class="progress-bar bg-warning" role="progressbar" aria-label="Info example" style="width: <%= @percentMedium %>%" aria-valuenow="<%= @percentMedium %>" aria-valuemin="0" aria-valuemax="100"><%= @percentMedium %>%</div>
      </div>
      <h3 class="mt-3">High Priority: </h3>
      <div class="progress" style="width: 35%;">
        <% @percentHigh =  (@tasks.where(priority: 'high').count.to_f / @count * 100).to_i %>
        <div class="progress-bar bg-danger" role="progressbar" aria-label="Success example" style="width: <%= @percentHigh %>%" aria-valuenow="<%= @percentHigh %>" aria-valuemin="0" aria-valuemax="100"><%= @percentHigh%>%</div>
      </div>

      <h2 class="row justify-content-md-center mt-5">Info about Lists</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>List Name</th>
            <th>Tasks ToDo</th>
            <th>Tasks inProgress</th>
            <th>Tasks Done</th>
            <th>Low Priority</th>
            <th>Medium Priority</th>
            <th>High Priority</th>
            <th>Total Tasks</th>
          </tr>
          </thead>
          <tbody>
            <% @lists.each do |list| %>
              <tr>
                <td><%= list.name %></td>
                <td><%= list.tasks.where(status: 'todo').count %></td>
                <td><%= list.tasks.where(status: 'progress').count %></td>
                <td><%= list.tasks.where(status: 'done').count %></td>
                <td><%= list.tasks.where(priority: 'low').count %></td>
                <td><%= list.tasks.where(priority: 'medium').count %></td>
                <td><%= list.tasks.where(priority: 'high').count %></td>
                <td><%= list.tasks.count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    <% end %>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% if notice.present? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_topnavbar.html.erb
<nav class="navbar navbar-expand-lg py-4 nav-pd-20">
    <div class="container-fluid">
        <%= link_to root_path do %>
            <img src="https://virtual360.io/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2020/04/Logo-Baixa.png.webp" style="max-width: 65%;" alt="Logo v360">
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to 'New List', new_list_path, class: "nav-link active nav-text" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'New Task', new_task_path, class: "nav-link active nav-text" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'All Tasks', tasks_path, class: "nav-link active nav-text" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Dashboard', dashboard_path, class: "nav-link active nav-text" %>
                </li>
            </ul>
            <li class="nav-item dropdown d-flex nav-user">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <% if user_signed_in? %>
                        <%= current_user.email %>
                    <% end %>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to 'Edit User', edit_user_registration_path, class:"dropdown-item" %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to 'Logout', destroy_user_session_path, class:"dropdown-item", method: :delete %></li>
                </ul>
            </li>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inicio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="icon" href="https://virtual360.io/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2020/04/Logo-Baixa.png.webp">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <%= render 'layouts/topnavbar' %>
    <%= render 'layouts/flash_messages' %>

    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="icon" href="https://virtual360.io/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2020/04/Logo-Baixa.png.webp">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <div class="row">
        <div class="col-md-7 d-none d-md-block div-brand">
          <div class="img-brand">
            <img src="https://virtual360.io/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2020/04/Logo-Baixa.png.webp" alt="Logo v360">
            <h1 class="h1-logo">TO DO</h1>
          </div>
        </div>
        
        <div class="col-md-5 d-flex justify-content-center text-center">
          <main class="form-signin w-100 m-auto p-5">
            <%= render 'layouts/flash_messages' %>
            <%= yield %>
            <p class="mt-5 mb-3 text-muted">V360&copy; 2022</p>
          </main>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, class: 'btn btn-lg mb-3 mt-3 button-login' %>
<% end %>

app/views/lists/edit.html.erb
<div class="row m-5 rounded p-5" style="background: #FFF;">
    <h1>Editing List</h1>

    <%= render 'form', list: @list %>
</div>

app/views/lists/index.html.erb
<% if @lists.count < 1 %>
  <h2 class="m-5">You have no list, click in link to create a new list: <%= link_to 'New List', new_list_path %></h2>
<% end %>
<% @lists.each do |list| %>
  
  <div class="row m-5 rounded p-5" style="background: #FFF;">
    <h1><%= list.name %></h1> 
    <div>
      <%= link_to edit_list_path(list) do %>
        <i class="fa fa-pen-to-square fa-xl p-1" style="color: #2C1A55"></i>
      <% end %>
      <%= link_to list, method: :delete, data: { confirm: "Are you sure delete '#{list.name}?'" } do %>
        <i class="fa fa-trash fa-xl p-1" style="color: #2C1A55"></i>
      <% end %>  
    </div>
    <div class="col-sm-4 mt-5">
      <div class="card">
        <div class="card-header" style="background: #FF700A;">To do</div>
        <div class="card-body">
          <% list.tasks.where(status: "todo").each do |task| %>
            
            <div class="card <%='card-'+task.priority%>">
              <div class="card-body">
                <h5 class="card-title"><%= task.name %></h5>
                <h6 class="card-subtitle mb-2 text-muted">
                  Priority: 
                  <% if task.priority.eql? 'high' %>
                    <span class="badge text-bg-danger"><%= task.priority %></span>
                  <% elsif task.priority.eql? 'medium' %>
                    <span class="badge text-bg-warning"><%= task.priority %></span>
                  <% else %>
                    <span class="badge text-bg-success"><%= task.priority %></span>
                  <% end %>
                </h6>
                <p class="card-text"><%= task.description %></p>
                <%= link_to 'Start Task', update_status_task_path(task, status: 'progress'), method: :patch %>
              </div>
              <div class="card-footer text-muted">
                <%= link_to edit_task_path(task) do %>
                  <i class="fa fa-pen-to-square fa-xl p-1" style="color: #2C1A55"></i>
                <% end %>
                <%= link_to task, method: :delete, data: { confirm: "Are you sure delete '#{task.name}'?"} do %>
                  <i class="fa fa-trash fa-xl p-1" style="color: #2C1A55"></i>
                <% end %>  
              </div>
            </div>          

          <% end %>
        </div>
      </div>
    </div>
    
    <div class="col-sm-4 mt-5">
      <div class="card">
        <div class="card-header" style="background: #FF700A;">In Progress</div>
        <div class="card-body">
          <% list.tasks.where(status: "progress").each do |task| %>
            
            <div class="card <%='card-'+task.priority%>">
              <div class="card-body">
                <h5 class="card-title"><%= task.name %></h5>
                <h6 class="card-subtitle mb-2 text-muted">
                  Priority: 
                  <% if task.priority.eql? 'high' %>
                    <span class="badge text-bg-danger"><%= task.priority %></span>
                  <% elsif task.priority.eql? 'medium' %>
                    <span class="badge text-bg-warning"><%= task.priority %></span>
                  <% else %>
                    <span class="badge text-bg-success"><%= task.priority %></span>
                  <% end %>
                </h6>
                <p class="card-text"><%= task.description %></p>
                <%= link_to 'Finish Task', update_status_task_path(task, status: 'done'), method: :patch %>
              </div>
              <div class="card-footer text-muted">
                <%= link_to edit_task_path(task) do %>
                  <i class="fa fa-pen-to-square fa-xl p-1" style="color: #2C1A55"></i>
                <% end %>
                <%= link_to task, method: :delete, data: { confirm: "Are you sure delete '#{task.name}'?" } do %>
                  <i class="fa fa-trash fa-xl p-1" style="color: #2C1A55"></i>
                <% end %>  
              </div>
            </div>          

          <% end %>
        </div>
      </div>
    </div>
    
    
    <div class="col-sm-4 mt-5">
      <div class="card">
        <div class="card-header" style="background: #FF700A;">Done</div>
          <div class="card-body">
            <% list.tasks.where(status: "done").each do |task| %>
            
              <div class="card <%='card-'+task.priority%>">
                <div class="card-body">
                  <h5 class="card-title"><%= task.name %></h5>
                  <h6 class="card-subtitle mb-2 text-muted">
                    Priority: 
                    <% if task.priority.eql? 'high' %>
                      <span class="badge text-bg-danger"><%= task.priority %></span>
                    <% elsif task.priority.eql? 'medium' %>
                      <span class="badge text-bg-warning"><%= task.priority %></span>
                    <% else %>
                      <span class="badge text-bg-success"><%= task.priority %></span>
                    <% end %>
                  </h6>
                  <p class="card-text"><%= task.description %></p>
                  <h6>Done <i class="fa-solid fa-check" style="color: #198754"></i></h6>
                </div>
                <div class="card-footer text-muted">
                  <%= link_to edit_task_path(task) do %>
                    <i class="fa fa-pen-to-square fa-xl p-1" style="color: #2C1A55"></i>
                  <% end %>
                  <%= link_to task, method: :delete, data: { confirm: "Are you sure delete '#{task.name}'?" } do %>
                    <i class="fa fa-trash fa-xl p-1" style="color: #2C1A55"></i>
                  <% end %>  
                </div>
              </div>
            <% end %>
          </div>
        </div>
    </div>
  </div>

<% end %>

app/views/lists/new.html.erb
<div class="row m-5 rounded p-5" style="background: #FFF;">
    <h1>New List</h1>

    <%= render 'form', list: @list %>

    <%= link_to 'Back', root_path %>
</div>

app/views/lists/show.html.erb
<div class="row m-5 rounded p-5" style="background: #FFF;">
  <p>
    <strong>Name:</strong>
    <%= @list.name %>
  </p>
</div>

app/views/tasks/_form_edit.html.erb
<%= simple_form_for task do |f| %>
  <%= f.input :name %>
  <%= f.input :description, input_html: { rows: 3 } %>
  <%= f.input :priority, collection: [['High', 'high'], ['Medium', 'medium'], ['Low', 'low']] %>
  <%= f.input :status, collection: [['ToDo', 'todo'], ['Progress', 'progress'], ['Done', 'done']] %>
  <%= f.association :list, collection: current_user.lists.all%>
  <%= f.button :submit, class: 'btn btn-lg mb-3 mt-3 button-login' %>
<% end %>

app/views/tasks/_form_new.html.erb
<%= simple_form_for task do |f| %>
  <%= f.input :name %>
  <%= f.input :description, input_html: { rows: 3 } %>
  <%= f.input :priority, collection: [['High', 'high'], ['Medium', 'medium'], ['Low', 'low']] %>
  <%= f.association :list, collection: current_user.lists.all%>
  <%= f.button :submit, class: 'btn btn-lg mb-3 mt-3 button-login' %>
<% end %>

app/views/tasks/edit.html.erb
<div class="row m-5 rounded p-5" style="background: #FFF;">
    <h1>Editing Task</h1>

    <%= render 'form_edit', task: @task %>
</div>

app/views/tasks/index.html.erb
<div class="row m-5 rounded p-5" style="background: #FFF;">
  <h1>Tasks</h1>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Status</th>
        <th>Priority</th>
        <th>List Name</th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.name %></td>
          <td><%= task.description %></td>
          <td><%= task.status %></td>
          <td>
            <% if task.priority.eql? 'high' %>
              <span class="badge text-bg-danger"><%= task.priority %></span>
            <% elsif task.priority.eql? 'medium' %>
              <span class="badge text-bg-warning"><%= task.priority %></span>
            <% else %>
              <span class="badge text-bg-success"><%= task.priority %></span>
            <% end %>
          </td>
          <td><%= task.list.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Back', root_path %>
</div>

app/views/tasks/new.html.erb
<div class="row m-5 rounded p-5" style="background: #FFF;">
  <h1>New Task</h1>

  <%= render 'form_new', task: @task %>

  <%= link_to 'Back', root_path %>
</div>

app/views/tasks/show.html.erb
<div class="row m-5 rounded p-5" style="background: #FFF;">
  <p>
    <strong>Name:</strong>
    <%= @task.name %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= @task.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @task.status %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= @task.priority %>
  </p>

  <p>
    <strong>List:</strong>
    <%= @task.list_id %>
  </p>
</div>